# Generated by Django 3.2.14 on 2022-07-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_feedback_id_alter_house_agreement_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house_details',
            name='house_location',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
